// camera_param_router.h
#ifndef CAMERA_PARAM_ROUTER_H
#define CAMERA_PARAM_ROUTER_H

#include <QString>
#include <optional>

// Enum for all camera parameters
enum class CameraParam {
    // RGB Streaming
    RGB_STREAMING_EXPOSURE,
    RGB_STREAMING_AUTO_EXPOSURE,
    RGB_STREAMING_EV_COMPENSATION,
    RGB_STREAMING_AUTO_FOCUS,
    RGB_STREAMING_LENS_POSITION,
    RGB_STREAMING_AUTO_ANALOG_GAIN,
    RGB_STREAMING_ANALOG_GAIN,
    RGB_STREAMING_DIGITAL_GAIN,
    RGB_STREAMING_AUTO_WB,
    RGB_STREAMING_RED_GAIN,
    RGB_STREAMING_BLUE_GAIN,
    RGB_STREAMING_COLOR_BALANCE_RED,
    RGB_STREAMING_COLOR_BALANCE_BLUE,
    RGB_STREAMING_FRAME_DURATION_ENABLED,
    RGB_STREAMING_FRAME_DURATION_US,
    // RGB Capture
    RGB_CAPTURE_EXPOSURE,
    RGB_CAPTURE_AUTO_EXPOSURE,
    RGB_CAPTURE_EV_COMPENSATION,
    RGB_CAPTURE_AUTO_FOCUS,
    RGB_CAPTURE_LENS_POSITION,
    RGB_CAPTURE_AUTO_ANALOG_GAIN,
    RGB_CAPTURE_ANALOG_GAIN,
    RGB_CAPTURE_DIGITAL_GAIN,
    RGB_CAPTURE_AUTO_WB,
    RGB_CAPTURE_RED_GAIN,
    RGB_CAPTURE_BLUE_GAIN,
    RGB_CAPTURE_COLOR_BALANCE_RED,
    RGB_CAPTURE_COLOR_BALANCE_BLUE,
    RGB_CAPTURE_RAW_MODE,
    RGB_CAPTURE_RAW_BIT_DEPTH,

    // Arducam Streaming
    ARDUCAM_STREAMING_EXPOSURE,
    ARDUCAM_STREAMING_AUTO_EXPOSURE,
    ARDUCAM_STREAMING_EV_COMPENSATION,
    ARDUCAM_STREAMING_AUTO_FOCUS,        
    ARDUCAM_STREAMING_LENS_POSITION,     
    ARDUCAM_STREAMING_ANALOG_GAIN,
    ARDUCAM_STREAMING_DIGITAL_GAIN,
    ARDUCAM_STREAMING_AUTO_WB,
    ARDUCAM_STREAMING_RED_GAIN,
    ARDUCAM_STREAMING_BLUE_GAIN,
    ARDUCAM_STREAMING_FRAME_DURATION_ENABLED,
    ARDUCAM_STREAMING_FRAME_DURATION_US,
    // Arducam Capture
    ARDUCAM_CAPTURE_EXPOSURE,
    ARDUCAM_CAPTURE_AUTO_EXPOSURE,
    ARDUCAM_CAPTURE_EV_COMPENSATION,
    ARDUCAM_CAPTURE_AUTO_FOCUS,          
    ARDUCAM_CAPTURE_LENS_POSITION,      
    ARDUCAM_CAPTURE_ANALOG_GAIN,
    ARDUCAM_CAPTURE_DIGITAL_GAIN,
    ARDUCAM_CAPTURE_AUTO_WB,
    ARDUCAM_CAPTURE_RED_GAIN,
    ARDUCAM_CAPTURE_BLUE_GAIN,
    ARDUCAM_CAPTURE_RAW_MODE,
    ARDUCAM_CAPTURE_RAW_BIT_DEPTH,

    // Thermal Streaming
    THERMAL_STREAMING_EMISSIVITY,
    THERMAL_STREAMING_MIN_TEMP,
    THERMAL_STREAMING_MAX_TEMP,
    THERMAL_STREAMING_COLORMAP,
    THERMAL_STREAMING_NUC_ENABLED,
    THERMAL_STREAMING_ALARM_ENABLED,
    THERMAL_STREAMING_ALARM_TEMP,

    // Thermal Capture
    THERMAL_CAPTURE_EMISSIVITY,
    THERMAL_CAPTURE_MIN_TEMP,
    THERMAL_CAPTURE_MAX_TEMP,
    THERMAL_CAPTURE_COLORMAP,
    THERMAL_CAPTURE_NUC_ENABLED,
    THERMAL_CAPTURE_ALARM_ENABLED,
    THERMAL_CAPTURE_ALARM_TEMP,

    // Depth Sensor
    DEPTH_TIMING_BUDGET,
    DEPTH_INTER_MEASUREMENT,
    DEPTH_SIGMA_THRESHOLD,
    DEPTH_SIGNAL_THRESHOLD,
    DEPTH_MEDIAN_FILTER_ENABLED,
    DEPTH_MEDIAN_FILTER_SAMPLES,
};

// Uses const char* internally for direct use with protocol constants
// Implicitly converts to QString when needed
struct CameraParamInfo {
    const char* camera;
    const char* parameter;
    const char* mode;
};

class CameraParamRouter {
public:
    // Returns routing info for a parameter, or nullopt if unknown
    static std::optional<CameraParamInfo> lookup(CameraParam param);
    
    // Helper to check if a param is an "auto" toggle that affects other controls
    static bool isAutoToggle(CameraParam param);
    
    // Get the related manual control for an auto toggle
    // e.g., RGB_STREAMING_AUTO_EXPOSURE -> RGB_STREAMING_EXPOSURE
    static std::optional<CameraParam> getRelatedManualParam(CameraParam autoParam);
};

#endif // CAMERA_PARAM_ROUTER_H
